### PR TITLE
201: S3 server-side encryption enabled rule

### PR DESCRIPTION
**Pull request by belosh59**

### CODE REVIEW

**Review by curphey — COMMENTED** [review]
This rules only checks if SSE is enabled but not if the KMS key is not owned by the account.

**Comment by curphey** [comment]
I am being lazy here but a few questions, more about discovery than the rule. 

1. Do we have info about if object encryption versus bucket encryption is enabled and which keys are used for that ?
2. Is there a way to determine what objects are made public (ie ones that override the bucket public policy) ?

**Comment by kickroot** [comment]
@curphey at this point we do not list, index, or grab properties for individual files inside buckets.  The scale of such an effort will likely require separate engineering for an out-of-band approach.

**Review by kickroot — APPROVED** [review]

**Comment by belosh59** [comment]
> I am being lazy here but a few questions, more about discovery than the rule.
> 
> 1. Do we have info about if object encryption versus bucket encryption is enabled and which keys are used for that ?
> 2. Is there a way to determine what objects are made public (ie ones that override the bucket public policy) ?

1. https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html  if we are talking about that than yes we have information (`"bucketKeyEnabled":true,` below). Regarding `which keys` -> Bucket encryption is allowed only for SSE-KMS encryption key type. We also have data about this which exact KMS Key was used for that 
```
"serverSideEncryptionConfiguration":{
      "rules":[
         {
            "bucketKeyEnabled":true,
            "applyServerSideEncryptionByDefault":{
               "sseAlgorithm":"aws:kms",
               "kmsMasterKeyID":"arn:aws:kms:us-west-1:723176279592:key/2f2f21f7-18d1-4991-8707-85f07cc15be6"
            }
         }
      ]
   }
```
2.  Jason already answered. Agree with him

**Comment by kickroot** [comment]
Looks good @belosh59, great work! :+1:

**Pull request merged**
